name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check gofmt
        run: |
          out=$(gofmt -s -l .)
          if [ -n "$out" ]; then echo "gofmt issues:\n$out"; exit 1; fi

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Go vet
        run: go vet ./...

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run unit tests
        run: go test ./...

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ledger_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Apply init SQL
        run: |
          psql "postgresql://postgres:postgres@localhost:5432/ledger_test?sslmode=disable" -f db/migrations/0001_init.sql
      - name: Run Postgres store tests
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ledger_test?sslmode=disable
        run: go test ./internal/storage/postgres -v

  openapi-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI
        run: |
          docker run --rm -v $PWD/openapi:/local openapitools/openapi-generator-cli validate -i /local/openapi.yaml

